version: '2'

services:
  node:
    image: node:8-alpine
    volumes:
      - .:/code
    working_dir: /code
    ports:
      - 8080:8080
    command: npm run serve

  # NGINX
  app:
    image: nginx:stable-alpine
    volumes:
      - .:/usr/share/nginx/html
    ports:
      - 81:80
    links:
      - node
